using Microsoft.AspNetCore.Mvc;
using ProductService.Models;
using ProductService.Services;

namespace ProductService.Controllers;

[ApiController]
[Route("api/products")]
public class ProductsController : ControllerBase
{
    private readonly ProductStore _productStore;

    // ProductStore is injected by ASP.NET Core Dependency Injection.
    public ProductsController(ProductStore productStore)
    {
        _productStore = productStore;
    }

    // GET /api/products
    [HttpGet]
    public ActionResult<List<Product>> GetAll()
    {
        return Ok(_productStore.GetAll());
    }

    // GET /api/products/1
    // OrderService will call THIS endpoint when creating an order.
    [HttpGet("{id:int}")]
    public ActionResult<Product> GetById(int id)
    {
        var product = _productStore.GetById(id);

        if (product is null)
        {
            return NotFound(new { message = $"Product with id {id} was not found." });
        }

        return Ok(product);
    }

    // POST /api/products
    [HttpPost]
    public ActionResult<Product> Create([FromBody] CreateProductRequest request)
    {
        if (string.IsNullOrWhiteSpace(request.Name))
        {
            return BadRequest(new { message = "Product name is required." });
        }

        if (request.Price <= 0)
        {
            return BadRequest(new { message = "Product price must be greater than 0." });
        }

        var product = _productStore.Add(request.Name, request.Price);

        return CreatedAtAction(nameof(GetById), new { id = product.Id }, product);
    }
}

// Request body for creating a product. Id is generated by ProductService, not by the client.
public class CreateProductRequest
{
    public string Name { get; set; } = string.Empty;
    public decimal Price { get; set; }
}
